services:
  - type: web
    name: vewo-site
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./_site
    envVars:
      - key: NODE_VERSION
        value: "20"
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
